# ~/.bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Uncomment the following line if you
# don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
if [ -d ~/.bashrc.d ]; then
	for rc in ~/.bashrc.d/*; do
		if [ -f "$rc" ]; then
			. "$rc"
		fi
	done
fi

unset rc


# Custom Commands
#
# Date: 2023/02/24
#
#
if [ -f $(which powerline-daemon) ]; then
    powerline-daemon -q
    POWERLINE_BASH_CONTINUATION=1
    POWERLINE_BASH_SELECT=1
    . /usr/share/powerline/bash/powerline.sh
fi

alias vi='vim'
alias pyserver='python -m http.server'
alias ipy='ipython'
alias tsh='trash'
alias ssup='sudo dnf upgrade'
alias lsbt='aria2c --show-files'

alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'

alias ls='ls -F --color=auto'
alias l.='ls -d .*'
alias ll='ls -alh'

alias q='exit'

alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias xzegrep='xzegrep --color=auto'
alias xzfgrep='xzfgrep --color=auto'
alias xzgrep='xzgrep --color=auto'
alias zegrep='zegrep --color=auto'
alias zfgrep='zfgrep --color=auto'
alias zgrep='zgrep --color=auto'

if [ -e ~/tLaunchShow ]; then
    cat ~/tLaunchShow
else
    touch ~/tLaunchShow
fi

